**Working ICP using open3d**

In [1]:
from icp import *
bag_filepath = "C:/Users/grzegorz.kunc/Desktop/RealsenseVideos/20201106_162933.bag"
pointclouds_dir_path = "./point_clouds"

ICP(bag_filepath, pointclouds_dir_path, max_frames = 5)

Getting frame...
Getting frame...
Getting frame...
Getting frame...
Getting frame...
calculating...
[[ 0.9997189   0.00529395 -0.02311054  0.01499223]
 [-0.00537316  0.9999799  -0.00336675  0.00487613]
 [ 0.02309225  0.00348998  0.99972725  0.00541489]
 [ 0.          0.          0.          1.        ]]
calculating...
[[ 0.99982471  0.00695404 -0.01738378  0.03038437]
 [-0.00701486  0.99996948 -0.00343999 -0.00179829]
 [ 0.01735933  0.00356133  0.99984297  0.03981407]
 [ 0.          0.          0.          1.        ]]
calculating...
[[ 0.99989045 -0.01302571 -0.00703013 -0.05501773]
 [ 0.01295503  0.99986599 -0.01000827  0.00856751]
 [ 0.00715955  0.0099161   0.9999252   0.1439048 ]
 [ 0.          0.          0.          1.        ]]
calculating...
[[ 0.99610548 -0.08528146  0.02238177 -0.13998356]
 [ 0.08570247  0.99614758 -0.01857664 -0.0724529 ]
 [-0.0207113   0.02042247  0.99957689  0.30217367]
 [ 0.          0.          0.          1.        ]]
================= TRANSFORMATION ==

In [2]:
import open3d as o3d


source = o3d.io.read_point_cloud("./point_clouds/1.ply") # Read the point cloud
source.paint_uniform_color([1, 0, 0]) # red

target = o3d.io.read_point_cloud("./point_clouds/5.ply") # Read the point cloud
target.paint_uniform_color([0, 1, 0]) # green

o3d.visualization.draw_geometries([source, target], width = 640, height = 480)

# ================================

In [27]:
source = o3d.io.read_point_cloud('cube.ply')
target = o3d.io.read_point_cloud('cube3.ply')
target.paint_uniform_color([1, 0, 0]) # red
threshold = 10
    
criteria = o3d.registration.ICPConvergenceCriteria(max_iteration = 50)
reg_p2p = o3d.registration.registration_icp(source, target, threshold, init = reg_p2p.transformation)
print(reg_p2p.transformation)
source_transformed = source.transform(reg_p2p.transformation)
source_transformed.paint_uniform_color([0, 1, 0]) # red

o3d.visualization.draw_geometries([target, source_transformed])
print(f"Expected translation norm: {np.linalg.norm(transformation, 'fro')}")
print(f"Given translation norm: {np.linalg.norm(reg_p2p.transformation, 'fro')}")


[[ 9.96190895e-01  3.06131621e-16  8.71992030e-02  2.00007308e-01]
 [ 7.60370100e-03  9.96190895e-01 -8.68670521e-02  2.00004993e-01]
 [-8.68670521e-02  8.71992030e-02  9.92396299e-01  2.00011980e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Expected translation norm: 2.029796324840046
Given translation norm: 2.029780705546479


**ICP for two images 2D**

**ICP for Points using vtk**