In [2]:
from loss_function import *
import numpy as np
import tensorflow as tf

# random testing values
# batch_size = 8

transform_true = tf.constant(np.random.rand(8,4,4))
ones = tf.constant(np.ones((8, 32, 1)))
        
y_source_net_selected = tf.constant(np.random.rand(8,32, 3))
y_target_net_calculated = tf.slice(tf.linalg.matmul(tf.concat([y_source_net_selected, ones], -1), transform_true), [0, 0, 0], [8, 32, 3])

lossFunction = LossFunction(y_source_net_selected, y_target_net_calculated, transform_true)
R, T = lossFunction.calculate_transform_pred()

print("TRANSFORMATION TRUE")
print(transform_true)
print("=======================")
print("TRANSFORMATIO PRED")
print(R, T)
print("=======================")

# print("SOURCE")
# print(y_source_net_selected)
# print("=======================")

# print("MULTIPLICATION")
# print(mult)
# print("=======================")



# construct class
# print(transform_true)

# loss1 = lossFunction.loss1()
# loss2 = lossFunction.loss2()
# print(loss1)
# print(loss2)

# loss = lossFunction.get_loss(0.3)
# print(loss)

(8, 3, 3)
TRANSFORMATION TRUE
tf.Tensor(
[[[0.33224186 0.71104458 0.13725613 0.57393896]
  [0.47031354 0.99627869 0.27171432 0.75876478]
  [0.49653151 0.59667082 0.30911854 0.50747106]
  [0.62828884 0.37001892 0.98947303 0.23267695]]

 [[0.87026842 0.2077004  0.65184454 0.33974066]
  [0.53790791 0.84649951 0.33332147 0.52089434]
  [0.05050741 0.86461667 0.75967639 0.27133487]
  [0.52049304 0.83965248 0.25579436 0.75559307]]

 [[0.87221173 0.73456478 0.22819825 0.08616764]
  [0.35554486 0.06588706 0.09102715 0.17185867]
  [0.60649903 0.0192748  0.62323392 0.03785904]
  [0.05873621 0.97718497 0.37685175 0.83570672]]

 [[0.79942137 0.2709293  0.17046821 0.92598936]
  [0.5262143  0.06723016 0.86833734 0.42129666]
  [0.66237851 0.08008684 0.44852594 0.48311569]
  [0.23438963 0.78220478 0.65893409 0.41726523]]

 [[0.53387998 0.9928175  0.32350577 0.93226899]
  [0.22459613 0.55202242 0.51088244 0.08529417]
  [0.80641336 0.58085952 0.63195383 0.6484713 ]
  [0.6573908  0.40797955 0.78764545 0.8

In [2]:
from loss import *

print(get_loss(alpha=0.5))

SyntaxError: invalid syntax (loss.py, line 29)

In [3]:
from loss_function import *
import numpy as np
import tensorflow as tf

transform_true = tf.eye(4, num_columns = 4, batch_shape = [4], dtype = tf.float64)
array = np.array([[1.0, 1.0, 1.0], [2.0, 2.0, 2.0], [3.0, 3.0, 3.0]])
y_source_net_selected = tf.constant([array, array, array, array], tf.float64)
y_target_net_calculated = tf.constant([array, array, array, array], tf.float64)
# print(y_source_net_selected)
# print(y_source_net_selected)                   
lossFunction = LossFunction(y_source_net_selected, y_target_net_calculated, transform_true)
lossFunction.get_loss(0.5)


<tf.Tensor: shape=(4,), dtype=float64, numpy=array([2.61682076e-16, 2.61682076e-16, 2.61682076e-16, 2.61682076e-16])>

In [6]:
from loss_function import *
import numpy as np
import tensorflow as tf

transform = np.array([[0.9962, 0, 0.0872, 0], [0, 1, 0, 0], [-0.0872, 0, 0.9962, 0], [0,0,0,0]])
print(transform)
print( np.transpose(transform))
# transform = np.array([[1.0, 2.0, 1.0, 1.0], [2.0, 1.0, 2.0, 2.0], [3.0, 3.0, 1.0, 3.0], [0.0, 0.0, 0.0, 1.0]])
transform_true = tf.constant((transform), dtype = tf.float64)
array = np.array([[1.0, 1.0, 1.0], [2.0, 2.0, 2.0], [3.0, 3.0, 3.0]])
array2 = np.array([[1.083350441, 1, 0.9090389553], [2.166700882, 2, 1.818077911], [3.250051323, 3, 2.727116866]])
y_source_net_selected = tf.constant([array, array, array, array, array], tf.float64)
y_target_net_calculated = tf.constant([array2, array2, array2, array2, array2], tf.float64)
# print(y_source_net_selected)
# print(y_source_net_selected)                                
lossFunction = LossFunction(y_source_net_selected, y_target_net_calculated, transform_true)
# lossFunction.calculate_transform_pred()

lossFunction.get_loss(0.5)

[[ 0.9962  0.      0.0872  0.    ]
 [ 0.      1.      0.      0.    ]
 [-0.0872  0.      0.9962  0.    ]
 [ 0.      0.      0.      0.    ]]
[[ 0.9962  0.     -0.0872  0.    ]
 [ 0.      1.      0.      0.    ]
 [ 0.0872  0.      0.9962  0.    ]
 [ 0.      0.      0.      0.    ]]


<tf.Tensor: shape=(5,), dtype=float64, numpy=array([0.46389885, 0.46389885, 0.46389885, 0.46389885, 0.46389885])>

In [21]:
R = tf.constant(np.array([[ 0.66790184, -0.39051369,  0.63356625],
         [-0.27361698,  0.66282358,  0.69699257],
         [ 0.69212779,  0.6388771 , -0.33584991]]))

T = tf.transpose(tf.constant(np.array([[-0.34025179,  0.35895084,  0.01066762]])))
lastRow = tf.reshape(tf.constant(np.array([0,0,0,1]), tf.float64), (1,4))
result = tf.concat([tf.concat([R, T], axis = -1), lastRow], axis = 0)
print(result)

tf.Tensor(
[[ 0.66790184 -0.39051369  0.63356625 -0.34025179]
 [-0.27361698  0.66282358  0.69699257  0.35895084]
 [ 0.69212779  0.6388771  -0.33584991  0.01066762]
 [ 0.          0.          0.          1.        ]], shape=(4, 4), dtype=float64)


[1.08641265 0.91118699 0.99470891]
